<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
      <UserSecretsId>a816d9db-1662-4664-9a52-b705877b4580</UserSecretsId>
  </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="9.0.5" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="9.0.5">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\StudentsSocial.Application\StudentsSocial.Application.csproj" />
        <ProjectReference Include="..\StudentsSocial.Core\StudentsSocial.Core.csproj" />
        <ProjectReference Include="..\StudentsSocial.Infrastructure\StudentsSocial.Infrastructure.csproj" />
        <ProjectReference Include="..\StudentsSocial.Persistence\StudentsSocial.Persistence.csproj" />
    </ItemGroup>

</Project>
