# This is a generated file. Not intended for manual editing.
services:
  students-social-api:
    build:
      context: "C:\\Users\\igorl\\OneDrive\\Desktop\\backend"
      dockerfile: "Dockerfile"
      target: "build"
    command: []
    entrypoint:
    - "dotnet"
    - "/app/bin/Debug/net9.0/backend.API.dll"
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
    image: "backend.api:dev"
    ports: []
    volumes:
    - "C:\\Users\\igorl\\OneDrive\\Desktop\\backend\\backend.API:/app:rw"
    - "C:\\Users\\igorl\\OneDrive\\Desktop\\backend:/src:rw"
    - "C:\\Users\\igorl\\.nuget\\packages:/root/.nuget/packages"
    working_dir: "/app"
